RegOwin/Models/CategoryViewModel.cs
using RegOwin.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RegOwin.Models
{
    public class CategoryViewModel
    {
        public string Name { get; set; }
        public List<NotebookParameterValues> Values { get; set; }
    }
}

RegOwin/Controllers/CartController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using RegOwin.Entities;
using RegOwin.Models.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using RegOwin.Filtres;

namespace RegOwin.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private AppUser CurrentUser { get { return UserManager.FindByName(HttpContext.User.Identity.Name); } }
        private AppContext Db
        {
            get { return HttpContext.GetOwinContext().Get<AppContext>(); }
        }
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        // GET: Cart
        public ActionResult Index()
        {
            Cart cart = Db.Carts
                .Include(c=>c.CartLines.Select(p=>p.Notebook))                
                .FirstOrDefault(p => p.UserId == CurrentUser.Id);
            return View(cart);
        }
        public void AddToCart(int id, int count=1)
        {
            Cart cart = Db.Carts
                .Include(p=>p.CartLines)              
                .FirstOrDefault(p => p.UserId == CurrentUser.Id);
            if (cart == null)
            {
                cart = new Cart { UserId = CurrentUser.Id};
                Db.Carts.Add(cart);                
            }
            CartLine cartline = cart.CartLines.FirstOrDefault(p => p.NotebookId == id && p.CartId==cart.Id);
            if (cartline==null)
            {
                cart.CartLines.Add(new CartLine { Count = count, Cart = cart, NotebookId = id });                
            }
            else
                cartline.Count += count;

            Db.SaveChanges();
        }
    }
}

RegOwin/Views/Shared/_Category.cshtml
@model List<RegOwin.Models.CategoryViewModel>

<div class="category">
    <h3 class="category-header">Категории</h3>
    <div class="category-list">
        @{var i = 1; }
        @foreach (var item in Model)
        {
            <div class="category-name" data-toggle="collapse" data-target="#notebook-list@(i)">@item.Name <span class="expand pull-right">+</span></div>
            <ul id="notebook-list@(i++)" class="collapse">
                @foreach (var t in item.Values)
                {

                    <li>
                        <label><input type="checkbox" data-category="@item.Name" data-id="@t.Id" />@t.Value</label>
                    </li>
                }
            </ul>
        }
    </div>
    <input type="hidden" name="checkedCheckbox" data-array="" />
</div>

<script>
    $(document).ready(function () {
        var c = $(".category-name");
        c.on("click", function () {
            $(":checkbox").on("change", function (e) {
                var getProducts = $(":checkbox:checked");
                getProducts = $.map(getProducts, function (s) {
                    return { Category: $(s).attr("data-category"), Id: $(s).attr("data-id") };
                });
                $("input[name='checkedCheckbox']").attr("data-array", JSON.stringify(getProducts));
                console.log($("input[name='checkedCheckbox']").attr("data-array"));
                $.ajax({
                    url: "Home/GetProducts",
                    success: function (data) {
                        $("#products").html(data);
                    },
                    data: JSON.stringify(getProducts),
                    type: "post",
                    contentType: "application/json"
                });
            });
            if ($(this).find("span").html() === "-")
                $(this).find("span").html("+");
            else
                $(this).find("span").html("-");
        });
    });
</script>

RegOwin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/HomeIndex.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />    
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/scripts/jquery-3.1.0.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <header id="header">
        <div class="topbar">
            <div class="container">
                <div class="social"></div>
                <ul class="nav pull-right login">@Html.Partial("_UserInfo")</ul>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="logo col-sm-3">
                <a href="#">logo</a>
            </div>
            <div class="seacrh col-sm-6 text-center">Тут будет поиск</div>
            <div class="cart col-sm-3">@Html.ActionLink("Корзина", "Index", "Cart",null, new { @class="pull-right"})</div>
        </div>
    </div>
    <div class="container">
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home</a></li>
                    </ul>
                </div>
            </div>

        </nav>
        @RenderBody()

        @if (TempData["message"] != null)
        {
            <div>@TempData["message"].ToString()</div>
        }

    </div>
    
</body>
</html>

RegOwin/Views/Shared/_NotebookInfo.cshtml
@model RegOwin.Entities.Notebook

<div class="notebook col-md-4">
    <div class="notebookImage">
        <a href="Home/NotebookInfo"><img src="@Model.Image" class="img-responsive" /></a>
    </div>
    <div class="notebookInfo">
        <div class="notebookTitle h4">@Model.Name</div>
        <div class="notebookDescription">@Model.Description</div>
        <div class="notebookPrice">
            @Model.Price
            @using (Ajax.BeginForm("AddToCart", "Cart", new AjaxOptions { HttpMethod = "Post", OnFailure = "f1" }))
            {
                @Html.HiddenFor(m => m.Id)
                <input type="submit" class="btn btn-default pull-right" value="В корзину" />
            }

        </div>

    </div>
</div>
<script>
    function f1(data,e) {
        alert(data.responseText);
        document.location.replace("http://localhost:55782/Account/Index");
    }
</script>

RegOwin/Views/Shared/_UserInfo.cshtml
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {

        <li>@HttpContext.Current.User.Identity.Name</li>
        <li>@Html.ActionLink("Выйти", "Logout", "Account")</li>

    }
    else
    {
        <li>@Html.ActionLink("Войти/Зарегистрироваться", "Index", "Account", new { returnUrl = @HttpContext.Current.Request.Url.AbsoluteUri }, null)</li>
    }